In [38]:
import numpy as np
import pandas as pd

In [39]:
_ARREST_KEY = "ARREST_KEY"

_ARREST_BORO = "ARREST_BORO"
_JURISDICTION_CODE = "JURISDICTION_CODE"
_OFFENSE_LEVEL = "LAW_CAT_CD"

_ARREST_DATE = "ARREST_DATE"
_ARREST_MONTH = "ARREST_MONTH" 

_ARREST_PRECINCT = "ARREST_PRECINCT"

_PERPETRATOR_RACE = "PERP_RACE"
_PERPETRATOR_SEX = "PERP_SEX"
_PERPETRATOR_AGE_GROUP="AGE_GROUP"

_INTERNAL_CLASSIFICATION="PD_CD"
_INTERNAL_CLASSIFICATION_DESCRIPTION="PD_DESC"
_THREE_DIGIT_INTERNAL_CLASSIFICATION="KY_CD"

_LAW_CODE="LAW_CODE"

_GEOGRAPHICAL_POSITION = "New Georeferenced Column"

_NYS_X_COORD = "X_COORD_CD"
_NYS_Y_COORD = "Y_COORD_CD"

_LATITUDE='Latitude'
_LONGITUDE='Longitude'


In [40]:
df = pd.read_csv('./cleaned_data.csv')
df.head()


OFNS_DESC    LAW_CODE LAW_CAT_CD ARREST_BORO  ARREST_PRECINCT  \
0  FELONY ASSAULT  PL-1211200          F           Q              105   
1  FELONY ASSAULT  PL-1200502          F           B               48   
2  FELONY ASSAULT  PL-1200512          F           S              121   
3  FELONY ASSAULT  PL-1211200          F           Q              100   
4            RAPE  PL-1302503          F           M               14   

   JURISDICTION_CODE   Latitude  Longitude ARREST_MONTH  
0                  0  40.737043 -73.735514      January  
1                  0  40.855109 -73.892818        March  
2                  0  40.628967 -74.163275          May  
3                  0  40.591980 -73.800066         June  
4                  0  40.753533 -73.994537      January

In [41]:
df.shape[1]

9

In [42]:
df[_ARREST_PRECINCT] = df[_ARREST_PRECINCT].astype('object')
df[_JURISDICTION_CODE] = df[_JURISDICTION_CODE].astype('object')

In [43]:
df_num= df.select_dtypes(exclude='object')
df_obj= df.select_dtypes(include='object')

df_num.info()
df_obj.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188682 entries, 0 to 188681
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   Latitude   188682 non-null  float64
 1   Longitude  188682 non-null  float64
dtypes: float64(2)
memory usage: 2.9 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188682 entries, 0 to 188681
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   OFNS_DESC          188682 non-null  object
 1   LAW_CODE           188682 non-null  object
 2   LAW_CAT_CD         188682 non-null  object
 3   ARREST_BORO        188682 non-null  object
 4   ARREST_PRECINCT    188682 non-null  object
 5   JURISDICTION_CODE  188682 non-null  object
 6   ARREST_MONTH       188682 non-null  object
dtypes: object(7)
memory usage: 10.1+ MB


In [44]:
df_obj[_OFFENSE_LEVEL].unique()
df_obj

OFNS_DESC    LAW_CODE LAW_CAT_CD ARREST_BORO  \
0                        FELONY ASSAULT  PL-1211200          F           Q   
1                        FELONY ASSAULT  PL-1200502          F           B   
2                        FELONY ASSAULT  PL-1200512          F           S   
3                        FELONY ASSAULT  PL-1211200          F           Q   
4                                  RAPE  PL-1302503          F           M   
...                                 ...         ...        ...         ...   
188677                    PETIT LARCENY  PL-1552500          M           Q   
188678     ASSAULT 3 & RELATED OFFENSES  PL-1200001          M           M   
188679                         BURGLARY  PL-1402501          F           M   
188680  OTHER OFFENSES RELATED TO THEFT  PL-1651503          M           B   
188681                DANGEROUS WEAPONS  PL-265031B          F           B   

       ARREST_PRECINCT JURISDICTION_CODE ARREST_MONTH  
0                  105                 0      January  
1                   48                 0        March  
2                  121                 0          May  
3                  100                 0         June  
4                   14                 0      January  
...                ...               ...          ...  
188677             109                 0    September  
188678              34                 0    September  
188679              23                 0    September  
188680              44                 1    September  
188681              46                 0    September  

[188682 rows x 7 columns]

In [45]:
# df_obj= pd.get_dummies(df_obj, drop_first=True)

# target = (df_obj['LAW_CAT_CD_M'])
# df_obj = df_obj.drop(columns=['LAW_CAT_CD_M'],axis=1)
# df_obj
target=df[_OFFENSE_LEVEL]
df_obj = df_obj.drop(columns=[_OFFENSE_LEVEL])

In [46]:
attr = pd.concat([df_obj,df_num],axis=1)


print(attr.shape[1])
attr.head()

8


OFNS_DESC    LAW_CODE ARREST_BORO ARREST_PRECINCT JURISDICTION_CODE  \
0  FELONY ASSAULT  PL-1211200           Q             105                 0   
1  FELONY ASSAULT  PL-1200502           B              48                 0   
2  FELONY ASSAULT  PL-1200512           S             121                 0   
3  FELONY ASSAULT  PL-1211200           Q             100                 0   
4            RAPE  PL-1302503           M              14                 0   

  ARREST_MONTH   Latitude  Longitude  
0      January  40.737043 -73.735514  
1        March  40.855109 -73.892818  
2          May  40.628967 -74.163275  
3         June  40.591980 -73.800066  
4      January  40.753533 -73.994537

In [47]:
from sklearn.model_selection import train_test_split

# Split the data into training and test
attr_train, attr_test, target_train, target_test = train_test_split(attr, target, test_size=0.30, random_state=5)

In [48]:
attr_train

OFNS_DESC    LAW_CODE ARREST_BORO  \
158385                  DANGEROUS DRUGS  PL-2200601           B   
145387                   FELONY ASSAULT  PL-1200502           B   
10483                           FORGERY  PL-1703000           Q   
68490           MISCELLANEOUS PENAL LAW  PL-21551B2           Q   
72030    CRIMINAL MISCHIEF & RELATED OF  PL-1450001           M   
...                                 ...         ...         ...   
121974     ASSAULT 3 & RELATED OFFENSES  PL-1200001           S   
124605                    PETIT LARCENY  PL-1552500           K   
20463   OTHER OFFENSES RELATED TO THEFT  PL-1651503           M   
18638                   DANGEROUS DRUGS  PL-2200300           B   
35683      ASSAULT 3 & RELATED OFFENSES  PL-1200001           B   

       ARREST_PRECINCT JURISDICTION_CODE ARREST_MONTH   Latitude  Longitude  
158385              46                 0       August  40.851843 -73.901190  
145387              42                 0         June  40.837685 -73.901571  
10483              115                 0      January  40.749258 -73.888976  
68490              114                 0         June  40.766513 -73.920035  
72030                6                 0          May  40.733876 -74.005428  
...                ...               ...          ...        ...        ...  
121974             122                 0         June  40.548608 -74.159983  
124605              81                 0         July  40.689640 -73.924051  
20463                6                 1       August  40.731707 -74.000956  
18638               52                 1        March  40.866070 -73.894382  
35683               50                 0      January  40.876494 -73.911698  

[132077 rows x 8 columns]

In [49]:
target_train

158385    F
145387    F
10483     F
68490     F
72030     M
         ..
121974    M
124605    M
20463     M
18638     M
35683     M
Name: LAW_CAT_CD, Length: 132077, dtype: object

In [50]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer


preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(
            handle_unknown="infrequent_if_exist"
            ), df_obj.columns.tolist()),
        ('num', StandardScaler(), df_num.drop(columns=[_LATITUDE,_LONGITUDE]).columns.tolist()),
    ],     remainder='passthrough'
)

In [33]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline


model = Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('classifier',KNeighborsClassifier())
])



In [34]:
model.fit (attr_train,target_train)


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='infrequent_if_exist'),
                                                  ['OFNS_DESC', 'LAW_CODE',
                                                   'ARREST_BORO',
                                                   'ARREST_PRECINCT',
                                                   'JURISDICTION_CODE',
                                                   'ARREST_MONTH']),
                                                 ('num', StandardScaler(),
                                                  ['Latitude', 'Longitude'])])),
                ('classifier', KNeighborsClassifier())])

In [36]:

target_pred = model.predict(attr_test)

In [37]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Evaluate the accuracy

#Compute and print the accuracy score.
accuracy = accuracy_score(target_test, target_pred)
print(f'Accuracy: {accuracy}')
print()

# Print the confusion matrix
print(confusion_matrix(target_test, target_pred))
print()

#Print the classification report
print('Classification Report')
print(classification_report(target_test, target_pred))

Accuracy: 0.9801430968995671

[[23475   696     2]
 [  324 31629     1]
 [   52    49   377]]

Classification Report
              precision    recall  f1-score   support

           F       0.98      0.97      0.98     24173
           M       0.98      0.99      0.98     31954
           V       0.99      0.79      0.88       478

    accuracy                           0.98     56605
   macro avg       0.98      0.92      0.95     56605
weighted avg       0.98      0.98      0.98     56605

